// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6AhzKMY9GKyp2I9qpvVir699oeXAP1i0',
    appId: '1:520898090513:web:e3c7274968e5b0602cc3b0',
    messagingSenderId: '520898090513',
    projectId: 'merlin-a65b2',
    authDomain: 'merlin-a65b2.firebaseapp.com',
    storageBucket: 'merlin-a65b2.appspot.com',
    measurementId: 'G-5PB7J0T5XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3groGMR0OltNEYpGWbLmme50GjkRpEU',
    appId: '1:520898090513:android:3d143d45e9dcf7082cc3b0',
    messagingSenderId: '520898090513',
    projectId: 'merlin-a65b2',
    storageBucket: 'merlin-a65b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wDWorPGAwA2Yvzx8bQ1HjQ7-gDFZ408',
    appId: '1:520898090513:ios:3da40adaebce74162cc3b0',
    messagingSenderId: '520898090513',
    projectId: 'merlin-a65b2',
    storageBucket: 'merlin-a65b2.appspot.com',
    iosClientId: '520898090513-34s7jrgrgadmuf923kdb8nbsn9309ls5.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.oop-class-flutter-template',
  );
}
